version: "3.5"

services:
  mlflow:
    env_file:
      - .env
    image: lanpn85/mlflow
    build: .
    ports:
      - 8111:5000
    volumes:
      - ./data:/data
    environment:
      MLF_BACKEND_STORE: 'sqlite:///data/mlflow.db'
